import React from 'react'
import moment from 'moment/moment'

export const defaultOfferStyles = [
    {
        id: 1,
        html: `<div style="margin: 10px 0px;"><div style="flex-direction: column; justify-content: center; align-items: center; position: relative;"><div style="width: 100%; min-height: 100%; justify-content: center; filter: drop-shadow(rgba(0, 0, 0, 0.2) 0px 0px 10px); border-radius: 10px; display: flex; position: relative; background-color: rgb(255, 255, 255);"><div class="flex-grow-1 d-flex flex-column justify-content-between" style="padding: 15px;"><div><div style="display: flex; flex-direction: column; align-items: start; justify-content: start; text-transform: uppercase;"><div style="font-weight: bolder; font-size: 0.9rem; color: rgb(255, 103, 28);">Q6TDK3OSVTH</div><span style="text-transform: lowercase; font-size: 0.75rem; color: rgb(0, 0, 0);">12% off Mango</span></div></div><div><div style="padding-top: 0.5rem;"><span style="text-transform: uppercase; font-weight: 500; font-size: 0.65rem;">valid until: Never ending</span></div></div></div><div style="display: flex; flex-direction: column; gap: 0.5rem; padding: 0px 15px 15px;"><div style="position: relative; display: flex; flex-direction: column; justify-content: space-between; align-items: center; background-color: rgb(255, 103, 28); padding: 1rem 0.25rem; border-radius: 0px 0px 5px 5px;"><h1 style="font-size: 1.829rem; font-weight: 750; font-family: Montserrat; color: rgb(255, 255, 255);">12%</h1></div><div style="display: flex; flex-direction: column; justify-content: flex-end; align-items: center;"><button type="button" style="color: rgb(255, 103, 28); font-size: 0.65rem; font-weight: 700; cursor: pointer; border: 0.75px solid rgb(255, 103, 28); border-radius: 15px; padding: 0.195rem; background-color: transparent; text-transform: uppercase;"><span>Redeem</span></button></div></div></div></div></div>`
    },
    {
        id: 2,
        html: `<div style="display: flex; border-radius: 500px; border: 1px solid rgb(0, 0, 0); margin: 10px 0px; background-color: #ffffff;"><div style="width: 50%; padding: 15px; display: flex; flex-direction: column; align-items: center; gap: 12.5px; border-right: 1px solid rgb(0, 0, 0);"><div style="font-weight: 700; font-size: 15px; color: #000000;">25% off</div><div style="font-size: 8px; color: #000000;">on order above Rs 1500</div></div><div style="width: 50%; padding: 15px; display: flex; flex-direction: column; align-items: center; gap: 15px;"><div style="font-size: 10px; color: #000000;">Offer Code</div><div style="font-weight: 700; font-size: 8px; color: #000000;">XIR25</div></div></div>`
    },
    {
        id: 3,
        html: `<div style="display: flex; flex-direction: column; margin: 10px 0px; gap: 15px; align-items: stretch; border-radius: 15px; padding: 15px;background-color: rgb(25, 151, 161);"><div style="display: flex; justify-content: space-between; gap: 15px;"><div style="font-size: 16px; color: white;">Discount on hotel rooms for two nights!</div><div style="font-size: 27.5px; font-weight: 600; color: white;">100%</div></div><div style="color: white; font-size: 12px;">Offer code: MGF09</div><div style="display: flex; justify-content: center; align-items: center;"><div style="font-size: 10px; color: rgb(255, 255, 255); border-radius: 25px; width: auto; max-width: 100%; padding: 10px 25px; background-color: rgb(227, 11, 92);">REDEEM</div></div></div>`
    },
    {
        id: 4,
        html: `<div style="display: flex; flex-direction: column; align-items: stretch; margin: 10px 0px; background-color: #ffffff"><div style="padding: 7.5px; border-bottom: 1px dashed black;"><div style="text-align: center; font-weight: 700; font-size: 12.5px; color: #000000">Get a FLAT 15% OFF on a spend of Rs. 1,499 and above!</div></div><div style="display: flex; flex-direction: column; align-items: stretch; padding: 7.5px 15px; gap: 15px;"><div style="display: flex; gap: 10px; justify-content: space-between; align-items: center;"><div style="display: flex; align-items: center; gap: 10px;"><svg xmlns="http://www.w3.org/2000/svg" width="20px" height="20px" viewBox="0 0 24 24" fill="#000000" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" class="feather feather-tag"><link xmlns="" type="text/css" id="dark-mode" rel="stylesheet" href=""/><style xmlns="" type="text/css" id="dark-mode-custom-style"/><path d="M20.59 13.41l-7.17 7.17a2 2 0 0 1-2.83 0L2 12V2h10l8.59 8.59a2 2 0 0 1 0 2.82z"/><line x1="7" y1="7" x2="7.01" y2="7"/></svg><div style="color: #000000">SUPERLX15</div></div><div style="font-size: 11px; background-color: rgb(28, 58, 86); color: #ffffff; border-radius: 6px; width: auto; max-width: 100%; padding: 10px">REDEEM</div></div><div style="text-align: center; font-size: 11px;color: #000000"><em>Redeem to auto-apply code at checkout!</em></div></div></div>`
    },
    {
        id: 5,
        html: `<div style="border: 2px dashed #000000; padding: 15px; display: flex; flex-direction: column; gap: 15px; margin: 10px 0px; background-color: #ffffff;"><div style="text-align: center; font-weight: 700; font-size: 13px; color: #000000;">Get a FLAT 15% OFF on a spend of Rs. 1,499 and above!​</div><div style="text-align: center; font-size: 12px; color: #000000;">Offer Code: SUPXL15</div><div style="display: flex; justify-content: center; align-items: center;"><div style="font-size: 12px; padding: 10px 35px; background-color: #000000; color: #ffffff; border-radius: 8px; width: auto;">Redeem</div></div></div>`
    },
    {
        id: 6,
        html: `<div style="display: flex; flex-direction: column; align-items: center; gap: 15px; padding: 15px; margin: 10px 0px; background-color: #ffffff;"><div style="text-align: center; font-size: 16px; color: #000000;">You have Unlock an ​​exclusive invite!</div><div style="text-align: center; font-size: 25px; font-weight: 600; color: #000000;">10% OFF</div><div style="display: flex; align-items: center; width: 100%;"><div style="width: 50%; text-align: center; color: #000000;"><u>Offer10</u></div><div style="width: 50%; text-align: center; display: flex; justify-content: center; align-items: center;"><div style="font-size: 15px; background-color: #000000; width: auto; padding: 10px 20px; border-radius: 5px; color: #ffffff;">Redeem</div></div></div></div>`
    },
    {
        id: 7,
        html: `<div style="padding: 15px; background-color: #fdb173; border-radius: 10px; display: flex; flex-direction: column; gap: 10px; margin: 10px 0px;"><div style="display: flex; justify-content: space-between; align-items: start; gap: 15px;"><div style="color: #ffffff; font-size: 16px;">40% off our premium facial and deluxe pedicure!</div><div style="font-size: 35px; color: #ffffff; font-weight: 700;">100%</div></div><div style="display: flex; justify-content: space-between; align-items: center; gap: 15px;"><div style="color: #ffffff; font-size: 12.5px;">​offer code: MGF09</div><div style="font-size: 15px; background-color: #ffffff; font-weight: 700; width: auto; color: #fdb173; padding: 7.5px 20px; border-radius: 5px;">Redeem</div></div></div>`
    },
    {
        id: 8,
        html: `<div style="display: flex; border-radius: 500px; background-color: #377f71; box-shadow: rgb(40, 40, 40) 0px 0px 10px 2.5px inset; margin: 10px 0px;"><div style="width: 50%; padding: 15px; display: flex; flex-direction: column; align-items: center; gap: 15px;"><div style="font-weight: 700; font-size: 20px; color: #ffffff">25% off</div><div style="font-size: 10px; color: #ffffff;">on order above Rs 1500</div></div><div style="width: 50%; padding: 15px; display: flex; flex-direction: column; align-items: center; gap: 15px;"><div style="font-size: 10px; color: #ffffff;">Offer Code</div><div style="font-weight: 700; font-size: 15px; color: #ffffff;">XIR25</div></div></div>`
    },
    {
        id: 9,
        html: `<div style="padding: 10px; display: flex; flex-direction: column; gap: 15px; margin: 10px 0px;"><div style="padding: 15px; display: flex; flex-direction: column; background-color: rgb(255, 117, 24); gap: 10px;  border-radius: 500px;"><div style="font-size: 15px; font-weight: 700; color: #ffffff;">Buy one desert and get the second free</div><div style="font-size: 10px; color: #ffffff;">Offer code: MGF09</div></div><div style="display: flex; justify-content: center; align-items: center;"><div style="background-image: linear-gradient(90deg, rgb(255, 117, 24), rgb(227, 11, 92)); border-radius: 25px; max-width: 100%; padding: 10px 25px; color: #ffffff; font-size: 12.5px;">REDEEM</div></div></div>`
    },
    {
        id: 10,
        html: `<div style="padding: 15px; background-color: rgb(255, 117, 24); display: flex; flex-direction: column; gap: 15px; border-radius: 500px; margin: 10px 0px;"><div style="font-size: 15px; color: #ffffff;">Buy one desert and get the second free</div><div style="display: flex; justify-content: space-between; align-items: center; gap: 15px;"><div style="font-size: 10px; color: #ffffff;">Offer code: MGF09</div><div style="display: flex; justify-content: center; align-items: center;"><div style="background-image: linear-gradient(90deg, rgb(255, 117, 24), rgb(227, 11, 92)); border-radius: 25px; max-width: 100%; padding: 10px 25px; color: #ffffff; font-size: 12.5px;">REDEEM</div></div></div></div>`
    }
]

const ReturnOfferHtml = ({ theme, details, colors }) => {

    const offerStyles = [
        {
            id: 1,
            html: `<div style="margin: 10px 0px;"><div style="flex-direction: column; justify-content: center; align-items: center; position: relative;"><div style="width: 100%; min-height: 100%; justify-content: center; filter: drop-shadow(rgba(0, 0, 0, 0.2) 0px 0px 10px); border-radius: 10px; display: flex; position: relative;  background-color: ${colors?.color_1 || "#ffffff"};"><div class="flex-grow-1 d-flex flex-column justify-content-between" style="padding: 15px;"><div><div style="display: flex; flex-direction: column; align-items: start; justify-content: start; text-transform: uppercase;"><div style="font-weight: bolder; font-size: 0.9rem; color: ${colors?.color_2 || "rgb(255, 103, 28)"};">${details?.Code}</div><span style="text-transform: lowercase; font-size: 0.75rem; color: ${colors?.color_3 || "rgb(0, 0, 0)"};">${details?.Summary}</span></div></div><div><div style="padding-top: 0.5rem;"><span style="text-transform: uppercase; font-weight: 500; font-size: 0.65rem; color: ${colors?.color_3 || "rgb(0, 0, 0)"}">valid until: ${details?.ValidityPeriod?.end ? moment(details?.ValidityPeriod?.end).format("YYYY-MM-DD HH:mm:ss") : "Never ending"}</span></div></div></div><div style="display: flex; flex-direction: column; gap: 0.5rem; padding: 0px 15px 15px;"><div style="position: relative; display: flex; flex-direction: column; justify-content: space-between; align-items: center; background-color: ${colors?.color_2 || "rgb(255, 103, 28)"}; padding: 1rem 0.25rem; border-radius: 0px 0px 5px 5px;"><div style="font-size: 1.829rem; font-weight: 750; font-family: Montserrat; color: ${colors?.color_1 || "#ffffff"};">${details?.Type === "PERCENTAGE" ? `${Math.ceil(details?.Value)}%` : `₹${Math.ceil(details?.Value)}`}</div></div><div style="display: flex; flex-direction: column; justify-content: flex-end; align-items: center;"><button type="button" style="color: ${colors?.color_2 || "rgb(255, 103, 28)"}; font-size: 0.65rem; font-weight: 700; cursor: pointer; border: 0.75px solid ${colors?.color_2 || "rgb(255, 103, 28)"}; border-radius: 15px; padding: 0.195rem; background-color: transparent; text-transform: uppercase;"><span>Redeem</span></button></div></div></div></div></div>`
            // html: `<div style="background-color: ${colors?.color_1 || "#ffffff"}; padding-left: 16px; padding-right: 16px; border-radius: 10px;"><div style="display: flex; justify-content: space-between"> <div> <div style="margin-top: 16px; color: ${colors?.color_2 || "rgb(255, 103, 28)"}; font-weight: bolder; margin-bottom: 0; ">${details?.Code}</div> <div style="color: ${colors?.color_3 || "rgb(0, 0, 0)"}; font-size: 13px; ">${details?.Summary}</div></div><div style="background-color: ${colors?.color_2 || "rgb(255, 103, 28)"}; border-bottom-left-radius: 6px; border-bottom-right-radius: 6px"><div style="font-size: 32px; font-weight: bolder; color: ${colors?.color_1 || "#ffffff"}; padding: 16px; ">${details?.Type === "PERCENTAGE" ? `${Math.ceil(details?.Value)}%` : `₹${Math.ceil(details?.Value)}`}/div></div></div><div style="display: flex; justify-content: space-between; margin-top: 0px; margin-top: 16px; padding-bottom: 16px"><div><div style="display: flex; justify-content: center; align-items: center; color: ${colors?.color_3 || "rgb(0, 0, 0)"}; padding-top: 6px; font-size: 12px;">VALID UNTIL: ${details?.ValidityPeriod?.end ? moment(details?.ValidityPeriod?.end).format("YYYY-MM-DD HH:mm:ss") : "Never ending"}</div></div><div style="display: flex; justify-content: flex-end"><div style="height: 25px; width: 60px; background-color: rgba(0, 0, 0, 0); color: ${colors?.color_2 || "rgb(255, 103, 28)"}; font-weight: bolder; border: 1px solid ${colors?.color_2 || "rgb(255, 103, 28)"}; border-radius: 20px; font-size: 12px; display: flex; justify-content: center; align-items: center; margin-right: 30px; margin-left: 10px;">REDEEM<div></div></div></div>`
        },
        {
            id: 2,
            html: `<div style="display: flex; border-radius: 500px; border: 1px solid ${colors?.color_3 || "rgb(0, 0, 0)"}; margin: 10px 0px; background-color: ${colors?.color_1 || "#ffffff"};"><div style="width: 50%; padding: 15px; display: flex; flex-direction: column; align-items: center; gap: 15px; border-right: 1px solid ${colors?.color_3 || "rgb(0, 0, 0)"};"><div style="font-weight: 700; font-size: 12.5px; color: ${colors?.color_2 || "#000000"};">${details?.Type === "PERCENTAGE" ? `${Math.ceil(details?.Value)}%` : `₹${Math.ceil(details?.Value)}`} off</div><div style="font-size: 8px; color: ${colors?.color_2 || "#000000"};">${details?.Summary}</div></div><div style="width: 50%; padding: 15px; display: flex; flex-direction: column; align-items: center; gap: 15px;"><div style="font-size: 8px; color: ${colors?.color_2 || "#000000"};">Offer Code</div><div style="font-weight: 700; font-size: 10px; color: ${colors?.color_2 || "#000000"};">${details?.Code}</div></div></div>`
        },
        {
            id: 3,
            html: `<div style="display: flex; flex-direction: column; margin: 10px 0px; gap: 15px; align-items: stretch; border-radius: 15px; padding: 15px;background-color: ${colors?.color_1 || "rgb(25, 151, 161)"};"><div style="display: flex; justify-content: space-between; gap: 15px;"><div style="font-size: 12.5px; color: ${colors?.color_3 || "#ffffff"};">${details?.Summary}</div><div style="font-size: 20px; font-weight: 600; color: ${colors?.color_3 || "#ffffff"};">${details?.Type === "PERCENTAGE" ? `${Math.ceil(details?.Value)}%` : `₹${Math.ceil(details?.Value)}`}</div></div><div style="color: ${colors?.color_3 || "#ffffff"}; font-size: 12px;">Offer code: ${details?.Code}</div><div style="display: flex; justify-content: center; align-items: center;"><div style="font-size: 10px; color: ${colors?.color_3 || "#ffffff"}; border-radius: 25px; width: auto; max-width: 100%; padding: 10px 25px; background-color: ${colors?.color_2 || "rgb(227, 11, 92)"};">REDEEM</div></div></div>`
        },
        {
            id: 4,
            html: `<div style="display: flex; flex-direction: column; align-items: stretch; margin: 10px 0px; background-color: ${colors?.color_1 || "#ffffff"};"><div style="padding: 7.5px; border-bottom: 1px dashed black;"><div style="text-align: center; font-weight: 700; font-size: 12.5px; color: ${colors?.color_3 || "#000000"}">${details?.Summary}</div></div><div style="display: flex; flex-direction: column; align-items: stretch; padding: 7.5px 15px; gap: 15px;"><div style="display: flex; gap: 10px; justify-content: space-between; align-items: center;"><div style="display: flex; align-items: center; gap: 10px;"><svg xmlns="http://www.w3.org/2000/svg" width="20px" height="20px" viewBox="0 0 24 24" fill="${colors?.color_3 || "#000000"}" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" class="feather feather-tag"><link xmlns="" type="text/css" id="dark-mode" rel="stylesheet" href=""/><style xmlns="" type="text/css" id="dark-mode-custom-style"/><path d="M20.59 13.41l-7.17 7.17a2 2 0 0 1-2.83 0L2 12V2h10l8.59 8.59a2 2 0 0 1 0 2.82z"/><line x1="7" y1="7" x2="7.01" y2="7"/></svg><div style="color: ${colors?.color_3 || "#000000"}; font-size: 11px;">${details?.Code}</div></div><div style="font-size: 11px; background-color: ${colors?.color_2 || "rgb(28, 58, 86)"}; color: ${colors?.color_1 || "#ffffff"}; border-radius: 6px; width: auto; max-width: 100%; padding: 10px">REDEEM</div></div><div style="text-align: center; font-size: 11px;color: ${colors?.color_3 || "#000000"}"><em>Redeem to auto-apply code at checkout!</em></div></div></div>`
        },
        {
            id: 5,
            html: `<div style="border: 2px dashed ${colors?.color_3 || "#000000"}; padding: 15px; display: flex; flex-direction: column; gap: 15px; margin: 10px 0px; background-color: ${colors?.color_1 || "#ffffff"};"><div style="text-align: center; font-weight: 700; font-size: 13px; color: ${colors?.color_3 || "#000000"};">${details?.Summary}​</div><div style="text-align: center; font-size: 12px; color: ${colors?.color_3 || "#000000"};">Offer Code: ${details?.Code}</div><div style="display: flex; justify-content: center; align-items: center;"><div style="font-size: 12px; padding: 10px 35px; background-color: ${colors?.color_2 || "#000000"}; color: ${colors?.color_1 || "#ffffff"}; border-radius: 8px; width: auto;">Redeem</div></div></div>`
        },
        {
            id: 6,
            html: `<div style="display: flex; flex-direction: column; align-items: center; gap: 15px; padding: 15px; margin: 10px 0px; background-color: ${colors?.color_1 || "#ffffff"};"><div style="text-align: center; font-size: 16px; color: ${colors?.color_3 || "#000000"};">${details?.Summary}</div><div style="text-align: center; font-size: 25px; font-weight: 600; color: ${colors?.color_3 || "#000000"};">${details?.Type === "PERCENTAGE" ? `${Math.ceil(details?.Value)}%` : `₹${Math.ceil(details?.Value)}`} OFF</div><div style="display: flex; align-items: center; width: 100%;"><div style="width: 50%; text-align: center; color: ${colors?.color_3 || "#000000"};"><u>${details?.Code}</u></div><div style="width: 50%; text-align: center; display: flex; justify-content: center; align-items: center;"><div style="font-size: 15px; background-color: ${colors?.color_2 || "#000000"}; width: auto; padding: 10px 20px; border-radius: 5px; color: ${colors?.color_1 || "#ffffff"};">Redeem</div></div></div></div>`
        },
        {
            id: 7,
            html: `<div style="padding: 15px; background-color: ${colors?.color_1 || "#fdb173"}; border-radius: 10px; display: flex; flex-direction: column; gap: 10px; margin: 10px 0px;"><div style="display: flex; justify-content: space-between; align-items: start; gap: 15px;"><div style="color: ${colors?.color_3 || "#ffffff"}; font-size: 16px;">${details?.Summary}</div><div style="font-size: 35px; color: ${colors?.color_3 || "#ffffff"}; font-weight: 700;">${details?.Type === "PERCENTAGE" ? `${Math.ceil(details?.Value)}%` : `₹${Math.ceil(details?.Value)}`}</div></div><div style="display: flex; justify-content: space-between; align-items: center; gap: 15px;"><div style="color: ${colors?.color_3 || "#ffffff"}; font-size: 12.5px;">​offer code: ${details?.Code}</div><div style="font-size: 15px; background-color: ${colors?.color_2 || "#ffffff"}; font-weight: 700; width: auto; color: ${colors?.color_1 || "#fdb173"}; padding: 7.5px 20px; border-radius: 5px;">Redeem</div></div></div>`
        },
        {
            id: 8,
            html: `<div style="display: flex; border-radius: 500px; background-color: ${colors?.color_1 || "#377f71"}; box-shadow: ${colors?.color_2 || "rgb(40, 40, 40)"} 0px 0px 10px 2.5px inset; margin: 10px 0px;"><div style="width: 50%; padding: 15px; display: flex; flex-direction: column; align-items: center; gap: 15px;"><div style="font-weight: 700; font-size: 20px; color: ${colors?.color_3 || "#ffffff"};">${details?.Type === "PERCENTAGE" ? `${Math.ceil(details?.Value)}%` : `₹${Math.ceil(details?.Value)}`} off</div><div style="font-size: 10px; color: ${colors?.color_3 || "#ffffff"};">${details?.Summary}</div></div><div style="width: 50%; padding: 15px; display: flex; flex-direction: column; align-items: center; gap: 15px;"><div style="font-size: 10px; color: ${colors?.color_3 || "#ffffff"};">Offer Code</div><div style="font-weight: 700; font-size: 15px; color: ${colors?.color_3 || "#ffffff"};">${details?.Code}</div></div></div>`
        },
        {
            id: 9,
            html: `<div style="padding: 10px; display: flex; flex-direction: column; gap: 15px; margin: 10px 0px;"><div style="padding: 15px; display: flex; flex-direction: column; background-color: ${colors?.color_1 || "rgb(255, 117, 24)"}; gap: 10px;  border-radius: 500px;"><div style="font-size: 15px; font-weight: 700; color: ${colors?.color_3 || "#ffffff"};">${details?.Summary}</div><div style="font-size: 10px; color: ${colors?.color_3 || "#ffffff"};">Offer code: ${details?.Code}</div></div><div style="display: flex; justify-content: center; align-items: center;"><div style="background-image: linear-gradient(90deg, ${colors?.color_1 || "rgb(255, 117, 24)"}, ${colors?.color_2 || "rgb(227, 11, 92)"}); border-radius: 25px; max-width: 100%; padding: 10px 25px; color: ${colors?.color_3 || "#ffffff"}; font-size: 12.5px;">REDEEM</div></div></div>`
        },
        {
            id: 10,
            html: `<div style="padding: 15px; background-color: ${colors?.color_1 || "rgb(255, 117, 24)"}; display: flex; flex-direction: column; gap: 15px; border-radius: 500px; margin: 10px 0px;"><div style="font-size: 15px; color: ${colors?.color_3 || "#ffffff"};">${details?.Summary}</div><div style="display: flex; justify-content: space-between; align-items: center; gap: 15px;"><div style="font-size: 10px; color: ${colors?.color_3 || "#ffffff"};">Offer code: ${details?.Code}</div><div style="display: flex; justify-content: center; align-items: center;"><div style="background-image: linear-gradient(90deg, ${colors?.color_1 || "rgb(255, 117, 24)"}, ${colors?.color_2 || "rgb(227, 11, 92)"}); border-radius: 25px; max-width: 100%; padding: 10px 25px; color: ${colors?.color_3 || "#ffffff"}; font-size: 12.5px;">REDEEM</div></div></div></div>`
        }
    ]

    // const offerStyle2 = [
    //     {
    //         id: 1,
    //         html: `<div style="margin: 10px 0px;"><div style="flex-direction: column; justify-content: center; align-items: center; position: relative;"><div style="width: 100%; min-height: 100%; justify-content: center; filter: drop-shadow(rgba(0, 0, 0, 0.2) 0px 0px 10px); border-radius: 10px; display: flex; position: relative;  background-color: ${mainObject?.offerProperties?.colors?.color_1 || "#ffffff"};"><div class="flex-grow-1 d-flex flex-column justify-content-between" style="padding: 15px;"><div><div style="display: flex; flex-direction: column; align-items: start; justify-content: start; text-transform: uppercase;"><div style="font-weight: bolder; font-size: 0.9rem; color: ${mainObject?.offerProperties?.colors?.color_2 || "rgb(255, 103, 28)"};">${Code}</div><span style="text-transform: lowercase; font-size: 0.75rem; color: ${mainObject?.offerProperties?.colors?.color_3 || "rgb(0, 0, 0)"};">${Summary}</span></div></div><div><div style="padding-top: 0.5rem;"><span style="text-transform: uppercase; font-weight: 500; font-size: 0.65rem; color: ${mainObject?.offerProperties?.colors?.color_3 || "rgb(0, 0, 0)"}">valid until: ${ValidityPeriod?.end ? moment(ValidityPeriod?.end).format("YYYY-MM-DD HH:mm:ss") : "Never ending"}</span></div></div></div><div style="display: flex; flex-direction: column; gap: 0.5rem; padding: 0px 15px 15px;"><div style="position: relative; display: flex; flex-direction: column; justify-content: space-between; align-items: center; background-color: ${mainObject?.offerProperties?.colors?.color_2 || "rgb(255, 103, 28)"}; padding: 1rem 0.25rem; border-radius: 0px 0px 5px 5px;"><div style="font-size: 1.829rem; font-weight: 750; font-family: Montserrat; color: ${mainObject?.offerProperties?.colors?.color_1 || "#ffffff"};">${Type === "PERCENTAGE" ? `${Math.ceil(Value)}%` : `₹${Math.ceil(Value)}`}</div></div><div style="display: flex; flex-direction: column; justify-content: flex-end; align-items: center;"><button type="button" style="color: ${mainObject?.offerProperties?.colors?.color_2 || "rgb(255, 103, 28)"}; font-size: 0.65rem; font-weight: 700; cursor: pointer; border: 0.75px solid ${mainObject?.offerProperties?.colors?.color_2 || "rgb(255, 103, 28)"}; border-radius: 15px; padding: 0.195rem; background-color: transparent; text-transform: uppercase;"><span>Redeem</span></button></div></div></div></div></div>`
    //     },
    //     {
    //         id: 2,
    //         html: `<div style="display: flex; border-radius: 500px; border: 1px solid ${mainObject?.offerProperties?.colors?.color_3 || "rgb(0, 0, 0)"}; margin: 10px 0px; background-color: ${mainObject?.offerProperties?.colors?.color_1 || "#ffffff"};"><div style="width: 50%; padding: 15px; display: flex; flex-direction: column; align-items: center; gap: 15px; border-right: 1px solid ${mainObject?.offerProperties?.colors?.color_3 || "rgb(0, 0, 0)"};"><div style="font-weight: 700; font-size: 12.5px; color: ${mainObject?.offerProperties?.colors?.color_2 || "#000000"};">${Type === "PERCENTAGE" ? `${Math.ceil(Value)}%` : `₹${Math.ceil(Value)}`} off</div><div style="font-size: 8px; color: ${mainObject?.offerProperties?.colors?.color_2 || "#000000"};">${Summary}</div></div><div style="width: 50%; padding: 15px; display: flex; flex-direction: column; align-items: center; gap: 15px;"><div style="font-size: 8px; color: ${mainObject?.offerProperties?.colors?.color_2 || "#000000"};">Offer Code</div><div style="font-weight: 700; font-size: 10px; color: ${mainObject?.offerProperties?.colors?.color_2 || "#000000"};">${Code}</div></div></div>`
    //     },
    //     {
    //         id: 3,
    //         html: `<div style="display: flex; flex-direction: column; margin: 10px 0px; gap: 15px; align-items: stretch; border-radius: 15px; padding: 15px;background-color: ${mainObject?.offerProperties?.colors?.color_1 || "rgb(25, 151, 161)"};"><div style="display: flex; justify-content: space-between; gap: 15px;"><div style="font-size: 12.5px; color: ${mainObject?.offerProperties?.colors?.color_3 || "#ffffff"};">${Summary}</div><div style="font-size: 20px; font-weight: 600; color: ${mainObject?.offerProperties?.colors?.color_3 || "#ffffff"};">${Type === "PERCENTAGE" ? `${Math.ceil(Value)}%` : `₹${Math.ceil(Value)}`}</div></div><div style="color: ${mainObject?.offerProperties?.colors?.color_3 || "#ffffff"}; font-size: 12px;">Offer code: ${Code}</div><div style="display: flex; justify-content: center; align-items: center;"><div style="font-size: 10px; color: ${mainObject?.offerProperties?.colors?.color_3 || "#ffffff"}; border-radius: 25px; width: auto; max-width: 100%; padding: 10px 25px; background-color: ${mainObject?.offerProperties?.colors?.color_2 || "rgb(227, 11, 92)"};">REDEEM</div></div></div>`
    //     },
    //     {
    //         id: 4,
    //         html: `<div style="display: flex; flex-direction: column; align-items: stretch; margin: 10px 0px; background-color: ${mainObject?.offerProperties?.colors?.color_1 || "#ffffff"};"><div style="padding: 7.5px; border-bottom: 1px dashed black;"><div style="text-align: center; font-weight: 700; font-size: 12.5px; color: ${mainObject?.offerProperties?.colors?.color_3 || "#000000"}">${Summary}</div></div><div style="display: flex; flex-direction: column; align-items: stretch; padding: 7.5px 15px; gap: 15px;"><div style="display: flex; gap: 10px; justify-content: space-between; align-items: center;"><div style="display: flex; align-items: center; gap: 10px;"><svg xmlns="http://www.w3.org/2000/svg" width="20px" height="20px" viewBox="0 0 24 24" fill="${mainObject?.offerProperties?.colors?.color_3 || "#000000"}" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" class="feather feather-tag"><link xmlns="" type="text/css" id="dark-mode" rel="stylesheet" href=""/><style xmlns="" type="text/css" id="dark-mode-custom-style"/><path d="M20.59 13.41l-7.17 7.17a2 2 0 0 1-2.83 0L2 12V2h10l8.59 8.59a2 2 0 0 1 0 2.82z"/><line x1="7" y1="7" x2="7.01" y2="7"/></svg><div style="color: ${mainObject?.offerProperties?.colors?.color_3 || "#000000"}; font-size: 11px;">${Code}</div></div><div style="font-size: 11px; background-color: ${mainObject?.offerProperties?.colors?.color_2 || "rgb(28, 58, 86)"}; color: ${mainObject?.offerProperties?.colors?.color_1 || "#ffffff"}; border-radius: 6px; width: auto; max-width: 100%; padding: 10px">REDEEM</div></div><div style="text-align: center; font-size: 11px;color: ${mainObject?.offerProperties?.colors?.color_3 || "#000000"}"><em>Redeem to auto-apply code at checkout!</em></div></div></div>`
    //     },
    //     {
    //         id: 5,
    //         html: `<div style="border: 2px dashed ${mainObject?.offerProperties?.colors?.color_3 || "#000000"}; padding: 15px; display: flex; flex-direction: column; gap: 15px; margin: 10px 0px; background-color: ${mainObject?.offerProperties?.colors?.color_1 || "#ffffff"};"><div style="text-align: center; font-weight: 700; font-size: 13px; color: ${mainObject?.offerProperties?.colors?.color_3 || "#000000"};">${Summary}​</div><div style="text-align: center; font-size: 12px; color: ${mainObject?.offerProperties?.colors?.color_3 || "#000000"};">Offer Code: ${Code}</div><div style="display: flex; justify-content: center; align-items: center;"><div style="font-size: 12px; padding: 10px 35px; background-color: ${mainObject?.offerProperties?.colors?.color_2 || "#000000"}; color: ${mainObject?.offerProperties?.colors?.color_1 || "#ffffff"}; border-radius: 8px; width: auto;">Redeem</div></div></div>`
    //     },
    //     {
    //         id: 6,
    //         html: `<div style="display: flex; flex-direction: column; align-items: center; gap: 15px; padding: 15px; margin: 10px 0px; background-color: ${mainObject?.offerProperties?.colors?.color_1 || "#ffffff"};"><div style="text-align: center; font-size: 16px; color: ${mainObject?.offerProperties?.colors?.color_3 || "#000000"};">${Summary}</div><div style="text-align: center; font-size: 25px; font-weight: 600; color: ${mainObject?.offerProperties?.colors?.color_3 || "#000000"};">${Type === "PERCENTAGE" ? `${Math.ceil(Value)}%` : `₹${Math.ceil(Value)}`} OFF</div><div style="display: flex; align-items: center; width: 100%;"><div style="width: 50%; text-align: center; color: ${mainObject?.offerProperties?.colors?.color_3 || "#000000"};"><u>${Code}</u></div><div style="width: 50%; text-align: center; display: flex; justify-content: center; align-items: center;"><div style="font-size: 15px; background-color: ${mainObject?.offerProperties?.colors?.color_2 || "#000000"}; width: auto; padding: 10px 20px; border-radius: 5px; color: ${mainObject?.offerProperties?.colors?.color_1 || "#ffffff"};">Redeem</div></div></div></div>`
    //     },
    //     {
    //         id: 7,
    //         html: `<div style="padding: 15px; background-color: ${mainObject?.offerProperties?.colors?.color_1 || "#fdb173"}; border-radius: 10px; display: flex; flex-direction: column; gap: 10px; margin: 10px 0px;"><div style="display: flex; justify-content: space-between; align-items: start; gap: 15px;"><div style="color: ${mainObject?.offerProperties?.colors?.color_3 || "#ffffff"}; font-size: 16px;">${Summary}</div><div style="font-size: 35px; color: ${mainObject?.offerProperties?.colors?.color_3 || "#ffffff"}; font-weight: 700;">${Type === "PERCENTAGE" ? `${Math.ceil(Value)}%` : `₹${Math.ceil(Value)}`}</div></div><div style="display: flex; justify-content: space-between; align-items: center; gap: 15px;"><div style="color: ${mainObject?.offerProperties?.colors?.color_3 || "#ffffff"}; font-size: 12.5px;">​offer code: ${Code}</div><div style="font-size: 15px; background-color: ${mainObject?.offerProperties?.colors?.color_2 || "#ffffff"}; font-weight: 700; width: auto; color: ${mainObject?.offerProperties?.colors?.color_1 || "#fdb173"}; padding: 7.5px 20px; border-radius: 5px;">Redeem</div></div></div>`
    //     },
    //     {
    //         id: 8,
    //         html: `<div style="display: flex; border-radius: 500px; background-color: ${mainObject?.offerProperties?.colors?.color_1 || "#377f71"}; box-shadow: ${mainObject?.offerProperties?.colors?.color_2 || "rgb(40, 40, 40)"} 0px 0px 10px 2.5px inset; margin: 10px 0px;"><div style="width: 50%; padding: 15px; display: flex; flex-direction: column; align-items: center; gap: 15px;"><div style="font-weight: 700; font-size: 20px; color: ${mainObject?.offerProperties?.colors?.color_3 || "#ffffff"};">${Type === "PERCENTAGE" ? `${Math.ceil(Value)}%` : `₹${Math.ceil(Value)}`} off</div><div style="font-size: 10px; color: ${mainObject?.offerProperties?.colors?.color_3 || "#ffffff"};">${Summary}</div></div><div style="width: 50%; padding: 15px; display: flex; flex-direction: column; align-items: center; gap: 15px;"><div style="font-size: 10px; color: ${mainObject?.offerProperties?.colors?.color_3 || "#ffffff"};">Offer Code</div><div style="font-weight: 700; font-size: 15px; color: ${mainObject?.offerProperties?.colors?.color_3 || "#ffffff"};">${Code}</div></div></div>`
    //     },
    //     {
    //         id: 9,
    //         html: `<div style="padding: 10px; display: flex; flex-direction: column; gap: 15px; margin: 10px 0px;"><div style="padding: 15px; display: flex; flex-direction: column; background-color: ${mainObject?.offerProperties?.colors?.color_1 || "rgb(255, 117, 24)"}; gap: 10px;  border-radius: 500px;"><div style="font-size: 15px; font-weight: 700; color: ${mainObject?.offerProperties?.colors?.color_3 || "#ffffff"};">${Summary}</div><div style="font-size: 10px; color: ${mainObject?.offerProperties?.colors?.color_3 || "#ffffff"};">Offer code: ${Code}</div></div><div style="display: flex; justify-content: center; align-items: center;"><div style="background-image: linear-gradient(90deg, ${mainObject?.offerProperties?.colors?.color_1 || "rgb(255, 117, 24)"}, ${mainObject?.offerProperties?.colors?.color_2 || "rgb(227, 11, 92)"}); border-radius: 25px; max-width: 100%; padding: 10px 25px; color: ${mainObject?.offerProperties?.colors?.color_3 || "#ffffff"}; font-size: 12.5px;">REDEEM</div></div></div>`
    //     },
    //     {
    //         id: 10,
    //         html: `<div style="padding: 15px; background-color: ${mainObject?.offerProperties?.colors?.color_1 || "rgb(255, 117, 24)"}; display: flex; flex-direction: column; gap: 15px; border-radius: 500px; margin: 10px 0px;"><div style="font-size: 15px; color: ${mainObject?.offerProperties?.colors?.color_3 || "#ffffff"};">${Summary}</div><div style="display: flex; justify-content: space-between; align-items: center; gap: 15px;"><div style="font-size: 10px; color: ${mainObject?.offerProperties?.colors?.color_3 || "#ffffff"};">Offer code: ${Code}</div><div style="display: flex; justify-content: center; align-items: center;"><div style="background-image: linear-gradient(90deg, ${mainObject?.offerProperties?.colors?.color_1 || "rgb(255, 117, 24)"}, ${mainObject?.offerProperties?.colors?.color_2 || "rgb(227, 11, 92)"}); border-radius: 25px; max-width: 100%; padding: 10px 25px; color: ${mainObject?.offerProperties?.colors?.color_3 || "#ffffff"}; font-size: 12.5px;">REDEEM</div></div></div></div>`
    //     }
    // ]

    return (
        <div dangerouslySetInnerHTML={{ __html: offerStyles.filter($ => $.id === theme)[0]?.html }} />
    )
}

export default ReturnOfferHtml